added mask of ones, if no mask is given
if mask is None, you will get an IndexError from
/skimage/registration/_masked_phase_cross_correlation.py", line 301, in _flip
reverse[axis] = slice(None, None, -1)
IndexError: list assignment index out of range